apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /auth(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "auth.fullname" . }}
                port:
                  number: 8000

          - path: /board(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "board.fullname" . }}
                port:
                  number: 8000

          - path: /profile(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "profile.fullname" . }}
                port:
                  number: 8000
