replicaCount: 2

image:
  repository: natalii571/board-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false

env:
  JWT_ALG: HS256
  ACCESS_TOKEN_EXPIRE_MINUTES: "15"
  REFRESH_TOKEN_EXPIRE_DAYS: "7"

database:
  host: board-db
  port: 5432
  name: boarddb
  user: boarduser
  password: boardpass


db:
  auth:
    username: boarduser
    password: boardpass
    database: boarddb
  persistence:
    size: 5Gi

#rabbitmq:
#  url: amqp://authuser:authpass@rabbitmq:5672/
