apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "board.fullname" . }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "board.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "board.name" . }}
    spec:

#      initContainers:
#        - name: db-migrate
#          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#          command: [ "alembic", "upgrade", "head" ]
#          envFrom:
#            - secretRef:
#                name: profile-profile-secrets


      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.port }}

          envFrom:
            - secretRef:
                name: {{include "board.fullname" . }}-secrets
            - configMapRef:
                name: {{ include "board.fullname" . }}-config

          readinessProbe:
            httpGet:
              path: /health/ready
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health/live
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 20


