apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "profile.fullname" . }}-config
data:
  JWT_ALG: {{ .Values.env.JWT_ALG | quote }}
  ACCESS_TOKEN_EXPIRE_MINUTES: "15"
  REFRESH_TOKEN_EXPIRE_DAYS: "7"

  DATABASE_HOST: {{ .Values.database.host | quote }}
  DATABASE_PORT: {{ .Values.database.port | quote }}
  DATABASE_NAME: {{ .Values.database.name | quote }}
  DATABASE_URL: "postgresql+asyncpg://profileuser:profilepass@profile-db:5432/profiledb"

  RABBITMQ_URL: {{ .Values.rabbitmq.url | quote }}

