apiVersion: v1
kind: Secret
metadata:
  name: {{ include "profile.fullname" . }}-secrets
type: Opaque
stringData:
  DATABASE_USER: {{ .Values.database.user | quote }}
  DATABASE_PASSWORD: {{ .Values.database.password | quote }}



  JWT_SECRET: "supersecret"
