apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth.fullname" . }}-config
data:
  JWT_ALG: {{ .Values.env.JWT_ALG | quote }}
  ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.env.ACCESS_TOKEN_EXPIRE_MINUTES | quote }}
  REFRESH_TOKEN_EXPIRE_DAYS: {{ .Values.env.REFRESH_TOKEN_EXPIRE_DAYS | quote }}

  DATABASE_HOST: {{ .Values.database.host | quote }}
  DATABASE_PORT: {{ .Values.database.port | quote }}
  DATABASE_NAME: {{ .Values.database.name | quote }}

  #DATABASE_URL: "postgresql+asyncpg://authuser:authpass@auth-db:5432/authdb"


