apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "auth.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "auth.name" . }}
    spec:
      containers:
        - name: auth
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.port }}

          env:
            - name: DATABASE_URL
              value: "postgresql+asyncpg://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"


            - name: RABBITMQ_URL
              value: "amqp://{{ .Values.global.rabbitmq.username }}:{{ .Values.global.rabbitmq.password }}@{{ .Values.global.rabbitmq.host }}:{{ .Values.global.rabbitmq.port }}/"



            - name: JWT_ALG
              value: "{{ .Values.env.JWT_ALG }}"

            - name: JWT_SECRET
              value: "{{ .Values.env.JWT_SECRET }}"

            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              value: "{{ .Values.env.ACCESS_TOKEN_EXPIRE_MINUTES }}"

            - name: REFRESH_TOKEN_EXPIRE_DAYS
              value: "{{ .Values.env.REFRESH_TOKEN_EXPIRE_DAYS }}"




          readinessProbe:
            httpGet:
              path: /health/ready
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health/live
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 20
