apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth.fullname" . }}-secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
stringData:
  JWT_SECRET: supersecret
  DATABASE_USER: {{ .Values.db.auth.username | quote }}
  DATABASE_PASSWORD: {{ .Values.db.auth.password | quote }}


  DATABASE_URL: postgresql+asyncpg://{{ .Values.db.auth.username }}:{{ .Values.db.auth.password }}@auth-db:5432/{{ .Values.db.auth.database }}
  RABBITMQ_URL: amqp://myuser:mypassword@rabbitmq:5672/
