apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth.fullname" . }}-secrets
type: Opaque
stringData:
  JWT_SECRET: supersecret
  DATABASE_USER: {{ .Values.db.auth.username | quote }}
  DATABASE_PASSWORD: {{ .Values.db.auth.password | quote }}
