apiVersion: v1
kind: Secret
metadata:
  name: {{ include "profile.fullname" . }}-secrets
type: Opaque
stringData:
  DATABASE_URL: postgresql+asyncpg://{{ .Values.db.auth.username }}:{{ .Values.db.auth.password }}@profile-db:5432/{{ .Values.db.auth.database }}
  JWT_SECRET: supersecret
  JWT_ALG: HS256
  ACCESS_TOKEN_EXPIRE_MINUTES: "15"
  REFRESH_TOKEN_EXPIRE_DAYS: "7"
  RABBITMQ_URL: amqp://myuser:mypassword@rabbitmq:5672/
